import requests

URL = "http://127.0.0.1:8000/api/canton_provincia/"
nombres = [
    "San José, San José",
    "San José, Escazú",
    "San José, Desamparados",
    "San José, Puriscal",
    "San José, Tarrazú",
    "San José, Aserrí",
    "San José, Mora",
    "San José, Goicoechea",
    "San José, Santa Ana",
    "San José, Alajuelita",
    "San José, Vásquez de Coronado",
    "San José, Acosta",
    "San José, Tibás",
    "San José, Moravia",
    "San José, Montes de Oca",
    "San José, Turrubares",
    "San José, Dota",
    "San José, Curridabat",
    "San José, Pérez Zeledón",
    "San José, León Cortés",
    "Alajuela, Alajuela",
    "Alajuela, San Ramón",
    "Alajuela, Grecia",
    "Alajuela, San Mateo",
    "Alajuela, Atenas",
    "Alajuela, Naranjo",
    "Alajuela, Palmares",
    "Alajuela, Poás",
    "Alajuela, Orotina",
    "Alajuela, San Carlos",
    "Alajuela, Zarcero",
    "Alajuela, Sarchí",
    "Alajuela, Upala",
    "Alajuela, Los Chiles",
    "Alajuela, Guatuso",
    "Alajuela, Río Cuarto",
    "Cartago, Cartago",
    "Cartago, Paraíso",
    "Cartago, La Unión",
    "Cartago, Jiménez",
    "Cartago, Turrialba",
    "Cartago, Alvarado",
    "Cartago, Oreamuno",
    "Cartago, El Guarco",
    "Heredia, Heredia",
    "Heredia, Barva",
    "Heredia, Santo Domingo",
    "Heredia, Santa Bárbara",
    "Heredia, San Rafael",
    "Heredia, San Isidro",
    "Heredia, Belén",
    "Heredia, Flores",
    "Heredia, San Pablo",
    "Heredia, Sarapiquí",
    "Guanacaste, Liberia",
    "Guanacaste, Nicoya",
    "Guanacaste, Santa Cruz",
    "Guanacaste, Bagaces",
    "Guanacaste, Carrillo",
    "Guanacaste, Cañas",
    "Guanacaste, Abangares",
    "Guanacaste, Tilarán",
    "Guanacaste, Nandayure",
    "Guanacaste, La Cruz",
    "Guanacaste, Hojancha",
    "Puntarenas, Puntarenas",
    "Puntarenas, Esparza",
    "Puntarenas, Buenos Aires",
    "Puntarenas, Montes de Oro",
    "Puntarenas, Osa",
    "Puntarenas, Quepos",
    "Puntarenas, Golfito",
    "Puntarenas, Coto Brus",
    "Puntarenas, Parrita",
    "Puntarenas, Corredores",
    "Puntarenas, Garabito",
    "Limón, Limón",
    "Limón, Pococí",
    "Limón, Siquirres",
    "Limón, Talamanca",
    "Limón, Matina",
    "Limón, Guácimo"
]

for nombre in nombres:
    response = requests.post(URL, json={"nombre": nombre})
    print(nombre, "→", response.status_code)
