# Generated by Django 5.2.7 on 2025-12-15 17:25

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resenha',
            name='puntuacion',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto_perfil',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
